export default [
  { path: "/static/images/brands/apc.jpg" },
  { path: "/static/images/brands/belton-pneumatica.jpg" },
  { path: "/static/images/brands/dichtomatik.jpg" },
  { path: "/static/images/brands/freudenberg.jpg" },
  { path: "/static/images/brands/hallite.jpg" },
  { path: "/static/images/brands/kastas.jpg" },
  { path: "/static/images/brands/merkel.jpg" },
  { path: "/static/images/brands/nak.jpg" },
  { path: "/static/images/brands/parker.jpg" },
  { path: "/static/images/brands/sabo.jpg" },
  { path: "/static/images/brands/sav.jpg" },
  { path: "/static/images/brands/simrit.jpg" },
  { path: "/static/images/brands/sistem-do-brasil.jpg" },
];
